# Prediction with LSTM model
<p style='text-align: right;'>with selectd1.csv</p>

In [3]:
def restart_kernel():
    # Restart the kernet after libraries are loaded.
    import IPython
    from datetime import datetime
    print(f'restart kernel... {datetime.now()}')
    app = IPython.Application.instance()
    app.kernel.do_shutdown(True)

In [ ]:
!pip install scikit-learn
!pip install tensorflow
from datetime import datetime
print(f'restart kernel... {datetime.now()}')

In [4]:
restart_kernel()

restart kernel... 2025-05-14 10:36:20.115647


In [ ]:
# load dependacies
import os
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from matplotlib import pyplot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

from lib.globalvar import *
from lib.data import DataLoader
from lib.model1 import PredictLSTM1
from lib.model2 import PredictLSTM2
from lib.model3 import PredictLSTM3
from lib.model4 import PredictLSTM4

import argparse
import matplotlib.pyplot as plt

from lib.util_pred import print_data
from lib.util_pred import flat_data_with_sum, flat_data, get_frequency
from lib.util_pred import save_model, import_mode
from lib.util_pred import get_random_in_list
from datetime import datetime

print(f"imported library. ({datetime.now()})")

In [3]:
model_classes = {'lstm1': PredictLSTM1,
                 'lstm2': PredictLSTM2,
                 'lstm3': PredictLSTM3,
                 'lstm4': PredictLSTM4}

window=1 # default = 1 , help = "time stamps"
data_dir='./selectd2.csv'
    
mode='predict' # help = "back-test or predict")
mode2='sampling' # help = "greed or sampling")
verb='verbose' # help = "verbose or not_verb")
    
trial=20 # help = "how much trials to generate")
training_length=1 # default = 0.9)
epoch=20 # default = 3
batch=1 # default = 1
model_type='lstm4' # help = "lstm1 or lstm2")
hid_dim = 50
print(f"finished to set environemnt. ({datetime.now()})")

finished to set environemnt. (2025-05-14 10:36:56.609019)


In [4]:
# data prepare and set base model
dataset = DataLoader(data_dir=data_dir,
                     training_length=training_length,
                     window_prev=window,
                     mode=mode,
                     from_pos=400
                    )
print(f'completed to load data. {datetime.now()}')

completed to load data. 2025-05-14 10:37:04.393621


In [5]:
## layers
"""
Activation (Output):
    linear: No activation, output is directly passed through.
    relu: Rectified Linear Unit, max(x, 0).
    sigmoid: Sigmoid function, output between 0 and 1.
    tanh: Hyperbolic tangent, output between -1 and 1.
    softmax: Normalizes output to a probability distribution.
    elu: Exponential Linear Unit.
    selu: Scaled Exponential Linear Unit.

Recurrent Activation:
    sigmoid: Commonly used for gates in LSTM.
    hard_sigmoid: A faster, less computationally expensive version of sigmoid.
    tanh: Can be used, but sigmoid is more typical for gates.
"""
layers = [LSTM(hid_dim,
               input_shape=(dataset.train_X.shape[1], dataset.train_X.shape[2]),
               activation="elu",
               return_sequences=True),
          LSTM(hid_dim,
               return_sequences=True,
               activation="elu"), #, recurrent_activation="tanh"),
          LSTM(hid_dim,
               return_sequences=True,
               activation="elu"), #, recurrent_activation="tanh"),
          LSTM(hid_dim,
               return_sequences=True,
               activation="elu"), #, recurrent_activation="tanh"),
          LSTM(hid_dim,
               return_sequences=True,
               activation="elu"), #, recurrent_activation="tanh"),
          LSTM(hid_dim,
               return_sequences=False,
               activation="elu",
               recurrent_activation="hard_sigmoid"),
          Dense(45, activation='softmax'),
          Dense(45, activation='sigmoid')]

/home/aimmodev/bin/clearml/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [6]:
model_class = model_classes[model_type]
print(f'start to create model. {datetime.now()}')
model = model_class(dataset, hid_dim = hid_dim, verb = verb, args=[layers])
print(f'comleted to create model. {datetime.now()}')

start to create model. 2025-05-13 13:44:50.475780
args = <class 'list'>, [[<LSTM name=lstm, built=False>, <LSTM name=lstm_1, built=False>, <LSTM name=lstm_2, built=False>, <Dense name=dense, built=False>, <Dense name=dense_1, built=False>]]
layers = <class 'list'>, [<LSTM name=lstm, built=False>, <LSTM name=lstm_1, built=False>, <LSTM name=lstm_2, built=False>, <Dense name=dense, built=False>, <Dense name=dense_1, built=False>]
layer = <class 'keras.src.layers.rnn.lstm.LSTM'>, <LSTM name=lstm, built=False>
layer = <class 'keras.src.layers.rnn.lstm.LSTM'>, <LSTM name=lstm_1, built=False>
layer = <class 'keras.src.layers.rnn.lstm.LSTM'>, <LSTM name=lstm_2, built=False>
layer = <class 'keras.src.layers.core.dense.Dense'>, <Dense name=dense, built=False>
layer = <class 'keras.src.layers.core.dense.Dense'>, <Dense name=dense_1, built=False>
PredictLSTM2.create_model <Sequential name=sequential, built=True>
comleted to create model. 2025-05-13 13:44:50.538860


In [6]:
# case of model2

model_class2 = model_classes[model_type]
print(f'start to create model. {datetime.now()}')
model2 = model_class2(dataset, hid_dim = hid_dim, verb = verb, args=[layers])
print(f'comleted to create model. {datetime.now()}')

start to create model. 2025-05-14 10:37:13.168555
args = <class 'list'>, [[<LSTM name=lstm, built=False>, <LSTM name=lstm_1, built=False>, <LSTM name=lstm_2, built=False>, <LSTM name=lstm_3, built=False>, <LSTM name=lstm_4, built=False>, <LSTM name=lstm_5, built=False>, <Dense name=dense, built=False>, <Dense name=dense_1, built=False>]]
layers = <class 'list'>, [<LSTM name=lstm, built=False>, <LSTM name=lstm_1, built=False>, <LSTM name=lstm_2, built=False>, <LSTM name=lstm_3, built=False>, <LSTM name=lstm_4, built=False>, <LSTM name=lstm_5, built=False>, <Dense name=dense, built=False>, <Dense name=dense_1, built=False>]
layer = <class 'keras.src.layers.rnn.lstm.LSTM'>, <LSTM name=lstm, built=False>
layer = <class 'keras.src.layers.rnn.lstm.LSTM'>, <LSTM name=lstm_1, built=False>
layer = <class 'keras.src.layers.rnn.lstm.LSTM'>, <LSTM name=lstm_2, built=False>
layer = <class 'keras.src.layers.rnn.lstm.LSTM'>, <LSTM name=lstm_3, built=False>
layer = <class 'keras.src.layers.rnn.lstm.LS

In [61]:
print(f'check to create model. {datetime.now()}')

check to create model. 2025-05-13 14:20:16.895243


In [ ]:
# training
# pass this.
from datetime import datetime
start_time = datetime.now()
hist = model.training(num_epoch = epoch, num_batch = batch)
end_time = datetime.now()
elapsed = end_time - start_time
print(f'elapsed = {elapsed}')
print(f'comleted to train model. {datetime.now()}')

In [7]:
# case of model2

# training
# pass this.
from datetime import datetime
start_time = datetime.now()
hist = model2.training(num_epoch = 50, num_batch = 1)
end_time = datetime.now()
elapsed = end_time - start_time
print(f'elapsed = {elapsed}')
print(f'comleted to train model. {datetime.now()}')

Epoch 1/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.0000e+00 - loss: 0.5659
Epoch 2/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0000e+00 - loss: 0.3066
Epoch 3/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0091 - loss: 0.2261
Epoch 4/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0086 - loss: 0.1885
Epoch 5/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0048 - loss: 0.1876
Epoch 6/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0056 - loss: 0.1602
Epoch 7/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0000e+00 - loss: 0.1638
Epoch 8/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 7.8595e-04 - loss: 0.1772
Epoch 9/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 0.1680
Epoch 10/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0081 - loss: 0.1601
Epoch 11/50
569/569 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 0.1647
Epoch 12/50
569/569 ━━━━━━━━

In [8]:
# predict
greed_prediction_number_set = model.predict_numbers("greed", trial=1)
random_pred_set = model.predict_randomely(trial=1)
#print(f'prediction_number_set = {prediction_number_set}')
print(f'comleted to predict model. {datetime.now()}')

comleted to predict model. 2025-05-13 07:07:01.105924


In [8]:
# case of model2
# model info
print(f'{model2.model.summary()}')

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 1, 50)          │        19,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 1, 50)          │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 1, 50)          │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 1, 50)          │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 1, 50)          │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 50)             │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 45)             │         2,295 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 45)             │         2,070 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 373,697 (1.43 MB)

 Trainable params: 124,565 (486.58 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 249,132 (973.18 KB)

None


In [ ]:
arams = {'bootstrap': False,
         'ccp_alpha': 0.0,
         'criterion': 'squared_error',
         'max_depth': 7,
         'max_features': 'sqrt',
         'max_leaf_nodes': None,
         'max_samples': None,
         'min_impurity_decrease': 0.0,
         'min_samples_leaf': 1,
         'min_samples_split': 50,
         'min_weight_fraction_leaf': 0.0,
         'monotonic_cst': None,
         'n_estimators': 1000,
         'n_jobs': -1,
         'oob_score': False,
         'random_state': None,
         'verbose': 0,
         'warm_start': False}

In [ ]:
# test
mode = "back-test"
if mode == 'back-test':
    model.evaluate(prediction_number_set)
    print("---------Random baseline-------------")
    model.evaluate(random_pred_set)

In [ ]:
# print result
print_data(title='wanted_data',
           data_set=[[3, 6, 7, 11, 12, 17]])
print_data(title='random_predicted',
           data_set=random_pred_set,
           add_val=1, need_sort=True)
# print_data(title='greed_predicted',
#            data_set=greed_prediction_number_set,
#            add_val=0, need_sort=True)

In [14]:
#flated_data = flat_data(prediction_number_set)
import itertools
flated_data = itertools.chain.from_iterable(greed_prediction_number_set)
print(f'{flated_data}')
frequency = get_frequency(flated_data)
frequency_sorted = dict(sorted(frequency.items()))
print(frequency_sorted)

{np.int64(7): 1, np.int64(16): 1, np.int64(18): 1, np.int64(21): 1, np.int64(44): 1, np.int64(45): 1}


In [15]:
print(model.model)

KerasRegressor(
	model=<function create_model_cb at 0x784bd6ed3240>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=binary_crossentropy
	metrics=None
	batch_size=1
	validation_batch_size=None
	verbose=0
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=50
	lstm_units=45
	dense_units=45
	train_X=[[[0. 1. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 1. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]]]
	activation=softmax
	learning_rate=0.001
)


In [ ]:
# draw model

import matplotlib.pyplot as plt
x_axis = list(frequency_sorted.keys())
y_axis = list(frequency_sorted.values())
plt.bar(x_axis, y_axis)
plt.xlabel("nums")
plt.ylabel("frequency")
plt.title("frequency")
plt.show()
print_data(title='wanted_data',
           data_set=[[5, 12, 24, 26, 39, 42, 20]])

In [9]:
# save model

model.save()

BaseLSTM.save_model


In [31]:
# model.verb = "None"
prediction_number_set3 = model.predict_numbers(mode2, trial=5, use_pre = True)
prediction_number_set4 = model.predict_numbers(mode2, trial=5, use_pre = False)

print_data(title='wanted_data',
           data_set=[[3, 6, 7, 11, 12, 17],
                    [5, 12, 24, 29, 32, 42],
                    [12, 13, 21, 26, 29, 37]])
print_data(title='prediction_number_set3',
           data_set=prediction_number_set3,
           add_val=0, need_sort=True)
print_data1(title='prediction_number_set4',
           data_set=prediction_number_set4,
           add_val=0, need_sort=True)

AttributeError: property 'verb' of 'PredictLSTM3' object has no setter

In [ ]:
for i in range(3):
    print(f'{i} : {get_random_in_list(prediction_number_set, 5)}')

In [ ]:
# model.verb = "None"
prediction_number_set = model.predict_numbers(mode2, trial=20, use_pre = True)

print_data(title='wanted_data',
           data_set=[[3, 6, 7, 11, 12, 17],
                     [3, 13, 28, 34, 38, 42],
                     [5, 12, 24, 29, 32, 42]])
print('-----')
for i in range(5):
    print(f'{i} : {get_random_in_list(prediction_number_set, 5)}')
print_data1(title="predicted_all", data_set=prediction_number_set)

In [ ]:
for i in range(5):
    print(f'{i} : {get_random_in_list(prediction_number_set, 5)}')

In [ ]:
# model.verb = "None"
prediction_number_set2 = model.predict_numbers(mode2, trial=40, use_pre = False)

print_data(title='wanted_data',
           data_set=[[3, 6, 7, 11, 12, 17],
                     [3, 13, 28, 34, 38, 42],
                     [5, 12, 24, 29, 32, 42]])
print('-----')
for i in range(5):
    print(f'{i} : {get_random_in_list(prediction_number_set2, 5)}')
print_data1(title="predicted_all", data_set=prediction_number_set2)

In [23]:
for i in range(5):
    print(f'{i} : {get_random_in_list(prediction_number_set2, 5)}')

0 : [1, 9, 17, 18, 24, 28]
1 : [4, 7, 14, 15, 29, 35]
2 : [7, 34, 37, 39, 41, 43]
3 : [8, 9, 10, 14, 18, 27]
4 : [1, 11, 18, 20, 25, 33]


In [ ]:
print_data(title='greed_predicted',
           data_set=greed_prediction_number_set,
           add_val=0, need_sort=True)
print(f'greed_prediction_number_set\n\t\t{greed_prediction_number_set}')

In [ ]:
# when 
"""
trial=20 # help = "how much trials to generate")
training_length=1 # default = 0.9)
epoch=100 # default = 3
batch=3 # default = 1
model='lstm2' # help = "lstm or lstm2")
hid_dim = 128
"""
for i in range(6):
    print(f'{i} : {get_random_in_list(prediction_number_set, 5)}')

In [ ]:
print(f'model={model}')

In [ ]:
random_pred_set = model.predict_randomely(trial=1)
print(f'prediction_number_set = {random_pred_set}')

In [ ]:
# 1170 : 3·13·28·34·38·42

last = [
    [6, 8, 37, 40, 41, 44],
    [8, 10, 20, 25, 33, 37],
    [4, 18, 27, 32, 40, 43],
    [2, 8, 10, 31, 33, 35],
    [15, 20, 28, 38, 41, 45],
    [12, 26, 13, 5, 31, 38]
]

In [24]:
#1171 : [3, 6, 7, 11, 12, 17]