In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Dense, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# 1. Prepare sample data
# Let's imagine we have some text data, represented as sequences of integers
# For simplicity, we'll create some dummy data
vocab_size = 1000  # Number of unique words in our vocabulary
max_len = 10       # Maximum length of our sequences
num_samples = 100  # Number of training samples

# Generate random sequences of integers
X_train = np.random.randint(1, vocab_size, size=(num_samples, max_len))
print('X_train = ', X_train)
print('X_train\'s len = ', len(X_train), len(X_train[0]))
y_train = np.random.randint(0, 2, size=(num_samples,)) # Binary classification target
print('y_train', y_train)
print('y_train', len(y_train))

# 2. Build the Bidirectional LSTM model
embedding_dim = 128
lstm_units = 64

model = Sequential([
    # Embedding layer to convert integer indices to dense vectors
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    
    # Bidirectional LSTM layer
    # 'merge_mode' can be 'concat' (default), 'sum', 'mul', 'ave', or None
    Bidirectional(LSTM(lstm_units, return_sequences=False)), 
    
    # Output Dense layer for classification
    Dense(1, activation='sigmoid') 
])

# 3. Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 4. Print model summary
model.summary()

# 5. (Optional) Train the model with your prepared data
# model.fit(X_train, y_train, epochs=10, batch_size=32)

X_train =  [[391 921 679 323 976 882 717 458 542 828]
 [323 284 770 616 889 719 225 351 811 354]
 [816 911 587 269   8 222 219 694 147 147]
 [951 422 402 472 906 922 425 772 120  55]
 [326 699 374 499 324 876 715 256 869 277]
 [219 139  56 605 944 768  29 673 538 869]
 [144 552 403  42 218 942 562 740 459 528]
 [631 705 677  72 848 871  45 299 350 550]
 [503 364 592 198 619 264 275 295  83   8]
 [249 158 112 191 738 763 839 925 316 308]
 [299 470 299 369 647 847 407 135  73 120]
 [954 254 663 393 542 152 561 893 184 577]
 [339 674 481 639 891 161 108 104 238 492]
 [565 725 326 870 694 932 254 338 397 965]
 [215 395 670 818 393  82 213 200  79 539]
 [126 489 135 341 770 572 292 683 171 724]
 [210 470 123 959 127 589 204 662 375 524]
 [ 80 729 389 694 365 451 929 714 643 738]
 [117  43  92 134 758 224 252 257 269 605]
 [177 317 601 685 101 766 769 897 287 828]
 [928 112 482 549 410 625 424 601 795  22]
 [347 495 540 178 845 275  13 796 687 388]
 [379 313 510 448 168 330 323 851  16 580]


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_3 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Bidirectional, LSTM, Dense, Embedding
from keras.preprocessing import sequence

# 1. Prepare Data (Example: IMDB movie review sentiment classification)
# Load the IMDB dataset
max_features = 20000  # vocabulary size
maxlen = 200          # sequence length
(x_train, y_train), (x_val, y_val) = keras.datasets.imdb.load_data(num_words=max_features)

# Pad sequences to a fixed length
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_val = sequence.pad_sequences(x_val, maxlen=maxlen)

# 2. Build the Multi-Layer Bidirectional LSTM Model
embedding_dim = 128
lstm_units_1 = 64
lstm_units_2 = 32

model = Sequential()
model.add(Embedding(max_features, embedding_dim)) # Embedding layer to convert word indices to dense vectors

# First Bidirectional LSTM layer
# return_sequences=True is crucial for stacking LSTM layers
model.add(Bidirectional(LSTM(lstm_units_1, return_sequences=True))) 

# Second Bidirectional LSTM layer
# The output of the first BiLSTM is fed as input to the second
model.add(Bidirectional(LSTM(lstm_units_2))) 

# Output layer for classification (e.g., binary classification for sentiment)
model.add(Dense(1, activation='sigmoid')) 

# 3. Compile the Model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 4. Model Summary (Optional, for understanding the architecture)
print(model.summary())

# 5. Train the Model (Example with dummy data)
# In a real scenario, you would train with your actual data
# history = model.fit(x_train, y_train, batch_size=32, epochs=5, validation_data=(x_val, y_val))